### ISSUE TITLE
Time for a new Benchmark.

### ISSUE THREAD

**Issue by DanielSokil** [anseki/cssprefix#1]

**Comment by anseki** [comment]
Hi @DanielSokil,
There is no description.

**Comment by DanielSokil** [comment]
@anseki It's mentioned in docs that benchmark is for older version, do the newer releases get slower or faster ?

**Comment by anseki** [comment]
I see.
The speed of the current version should not be changed because cache system was not changed.

**Comment by DanielSokil** [comment]
Thank you for your response.

**Comment by anseki** [comment]
:smile:
